/** 教材编译与取证容量护栏（§13.2 配置 Owner）。 */
export const LEARNING_SKELETON_MAX_EVIDENCE_FRAGMENTS = 24
export const LEARNING_SKELETON_MAX_INITIAL_NODES = 24
export const LEARNING_EVIDENCE_PER_FILE_MAX_BYTES = 256 * 1024
export const LEARNING_MAX_COMPILE_OUTPUT_BYTES = 256 * 1024
export const LEARNING_SCHEMA_REPAIR_MAX_EXTRA_CALLS = 1
export const LEARNING_EVIDENCE_TOTAL_MAX_BYTES = 48 * 1024
export const LEARNING_DISCOVERY_MAX_ENTRIES = 4096
export const LEARNING_COMPILE_MAX_INPUT_TOKENS = 16000
