export const LEARNING_MAX_TEXT_LENGTH = 8_000
export const LEARNING_MAX_OPTION_IDS = 12
export const LEARNING_MAX_OPTION_ID_LENGTH = 64
export const LEARNING_MAX_NODE_ID_LENGTH = 128
export const LEARNING_MAX_COMMAND_ID_LENGTH = 128
export const LEARNING_MAX_REFERENCES = 32
