/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\renderer\styles\astryx-parchment-theme.ts
 * Command: astryx theme build src\renderer\styles\astryx-parchment-theme.ts --out src\renderer\styles\astryx-parchment.css
 * Generated: 2026-09-19T18:51:51.518Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
