/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\renderer\styles\astryx-parchment-theme.ts
 * Command: astryx theme build src\renderer\styles\astryx-parchment-theme.ts --out src\renderer\styles\astryx-parchment.css
 * Generated: 2026-08-03T08:03:55.949Z
 */

/// <reference path="./parchment.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const parchmentTheme: DefinedTheme;
